### ISSUE TITLE
My is MAC Address necessary?

### ISSUE THREAD

**Issue by robross0606** [stjohnjohnson/smartthings-mqtt-bridge#121]
The native app asks for the IP, port _and_ the MAC address of the bridge system.  Why is the MAC address necessary?

**Comment by stjohnjohnson** [comment]
Yes, the SmartThings local incoming calls work by whitelisting by MAC address.  And outgoing calls work by IP.  Kinda insane actually.

**Comment by stjohnjohnson** [comment]
Mac Address usage: https://github.com/stjohnjohnson/smartthings-mqtt-bridge/blob/11da327d4132b81a1383d748c90a1bcb713ccee3/devicetypes/stj/mqtt-bridge.src/mqtt-bridge.groovy#L59

IP Address Usage: https://github.com/stjohnjohnson/smartthings-mqtt-bridge/blob/11da327d4132b81a1383d748c90a1bcb713ccee3/devicetypes/stj/mqtt-bridge.src/mqtt-bridge.groovy#L98
