### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by bhaap** [stjohnjohnson/smartthings-mqtt-bridge#123]
Is there a way for this smartapp to work offline? noticed that without internet the mqtt bridge did not work. Sensors where reacting but nothing was sent to my mqtt server. Only local ip-adresses where used in setting the bridge up.

**Comment by stjohnjohnson** [comment]
Sadly no.  With each release of SmartThings, they still don't offer SmartApp or DeviceTypes that interact with LAN to work offline.  I've asked many times. :(
