### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by timbiotic** [stjohnjohnson/smartthings-mqtt-bridge#125]
I see traffic both ways but my control from HA to smartthings hub failes.  Any idea what i am missing?  I didnt see anywhere were we need to put in credentials.  

info: Incoming message from MQTT: smartthings/Basement Back/switch = on
"error: Error from SmartThings Hub: Error: connect ECONNREFUSED 192.168.69.181:39500"

"code": "ECONNREFUSED",
"errno": "ECONNREFUSED",
"syscall": "connect",
"address": "192.168.69.181",
"port": 39500
}

**Comment by jmoery** [comment]
I'm having the same issue.  Anyone know what typically triggers this?  Everything was working fine, now it's not.

**Comment by jmoery** [comment]
Fyi, I was able to fix this by  removing the smartthings bridge device in the native app and re-adding it with all the associated devices.  Seems that got out of sync somehow.

**Comment by timbiotic** [comment]
I got mine fixed by rebooting my smart things hub... weird
