### ISSUE TITLE
Allow duplicate messages selectively

### ISSUE THREAD

**Issue by almostserious** [stjohnjohnson/smartthings-mqtt-bridge#140]
Is it possible to selectively allow duplicate messages for certain devices?
I'd like to send the unlock command for my lock even if its already set to unlock.

(Locked = Completely locked. If the door is just closed, the lock is also set at unlock and im unable to send the unlock command again from HA)

**Comment by digiblur** [comment]
The whole duplicate message thing really ruins the bridge for me.  It seems about 90% of the time I can never toggle the items in HA as the bridge thinks its a duplicate message.  I have to delete the state it has saved for the device then restart the bridge.  But then it goes right back to not working later after things toggle.  I figured it is probably easier to just ditch ST.

**Comment by airdrummingfool** [comment]
This may be fixed by my PR #136, which simplified the deduplication logic and reduced the situations in which it kicks in. That PR was merged and released as [2.1.0](https://github.com/stjohnjohnson/smartthings-mqtt-bridge/releases/tag/v2.1.0). Try it out and see if it works!

**Comment by almostserious** [comment]
Yes finally got around to test the new release. It works in 3.0.0
