### ISSUE TITLE
MAC address

### ISSUE THREAD

**Issue by dennyreiter** [stjohnjohnson/smartthings-mqtt-bridge#151]
I think I might be closer to fixing my problem.  In the device where it asks for your mac address, what is that used for, a unique ID?  I noticed grailExceptions in the ST livelogging about a unique ID, and I'm also using the Google Assistant relay on the same box, and it also used the mac address.  Can I use a different ID, instead so they don't conflict?

**Comment by dmwyatt** [comment]
The SmartThings hub won't accept connections from your HA device unless the mac address of the request matches the mac address you configure for the MQTT Device.
