### ISSUE TITLE
unable to controle

### ISSUE THREAD

**Issue by ajdezigns** [stjohnjohnson/smartthings-mqtt-bridge#160]
since the latest updates to SmartThings i'm still reating state values but i'm no longer able to push commands to SmartThings everything looks to be fine though on home assistant in the smartthings-mqtt-bridge app i can see the request has been sent from the MQTT server requesting the light turn on but Samsung does not seam to receive the request

**Comment by angel12** [comment]
I am having the same issue on my setup, and I get this error in the docker console:
error: Error from SmartThings Hub: Error: connect EHOSTUNREACH <ip-of-sthub>:39500 
error: {                                                                        
    "errno": "EHOSTUNREACH",                                                    
    "code": "EHOSTUNREACH",                                                     
    "syscall": "connect",                                                       
    "address": "<ip-of-sthub>",                                                    
    "port": 39500
