### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by vvallee** [stjohnjohnson/smartthings-mqtt-bridge#161]
I've followed the documentation several times over, and I cannot seem to get any data between Samsung's API and Hass. The mqtt-bridge starts and runs, and seems to send and receive messages from my mosquitto server but that's it. Nothing from SmartThings. :(

Also the docker image does not want to compile.

```
Status: Image is up to date for stjohnjohnson/smartthings-mqtt-bridge:latest
root@controller:/opt/mqtt-bridge# docker run     -d     --name="mqtt-bridge"     -v /opt/mqtt-bridge:/config     -p 8080:8080     stjohnjohnson/sma^Cthings-mqtt-bridge
root@controller:/opt/mqtt-bridge# docker run \
>     -d \
>     --name="mqtt-bridge" \
>     -v /opt/mqtt-bridge:/config \
>     -p 8080:8080 \
>     stjohnjohnson/smartthings-mqtt-bridge
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
31dbfea7cfb52816f0fb85c7c174ff7e6974a763281a6bb6785b0644b39e1189
Error response from daemon: Cannot start container 31dbfea7cfb52816f0fb85c7c174ff7e6974a763281a6bb6785b0644b39e1189: [8] System error: exec format error
```

**Comment by vvallee** [comment]
Any help appreciated, I feel naked without my Smart home working! :)

**Comment by stjohnjohnson** [comment]
Are you running this from a Raspberry Pi or something else?

**Comment by vvallee** [comment]
Thanks for your reply, yes in this case a raspberry Pi 3-B on Raspbian stretch.

**Comment by stjohnjohnson** [comment]
Ahh. Then that docker image won’t work. It’s or compiles for ARM. There is
one around here. Might be in the repo.

**Comment by vvallee** [comment]
That makes sense. Thanks!
