### ISSUE TITLE
How does this project detect new devices from a MQTT server?

### ISSUE THREAD

**Issue by markg85** [stjohnjohnson/smartthings-mqtt-bridge#183]
Hi,

After some configuration pain i managed to get it working as per the description on this project's main page.

Now i have some devices in my smartthings already, those do show up in the appropriate places onder this project's (in the smartapp). I did (just fur fun) add an existing device and am now able to control that device through MQTT.

That on it's own is great! But it's not what i'm looking for :)

Now i have some other devices that communicate through various means. One of them is MQTT. Those devices aren't known yet in smartthings. I was hoping that those devices, once they broadcast themselves on MQTT, would automatically become visible in smartthings with this project.

So the route would be:
<device> -> MQTT -> smartthings-mqtt-bridge -> SmartThings

Once there it would be able to control the device through the smartthings app.
Or, in a more fancy way, though the google home integration of smartthings that device would then become available in google home! Which is the ultimate goal here for me.

I really hope this project can also do the reverse. So do: "make devices from MQTT available in SmartThings". Can it?

Cheers,
Mark

**Comment by stjohnjohnson** [comment]
Hey Mark,

That's a fascinating request.  I'm not really sure how to accomplish that.  You would need to build a SmartApp that could create virtual devices on demand and configure them.

This is _way_ outside of this project's scope.  But still a cool idea.
