### ISSUE TITLE
execution expired (HTTPClient::ReceiveTimeoutError)

### ISSUE THREAD

**Issue by umapathireddy** [stjohnjohnson/smartthings-mqtt-bridge#187]
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
execution expired (HTTPClient::ReceiveTimeoutError)
D:/Ruby23/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `gets'
D:/Ruby23/lib/ruby/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `block in parse_header'
D:/Ruby23/lib/ruby/2.3.0/timeout.rb:101:in `timeout'

**Comment by stjohnjohnson** [comment]
Nothing in our code has ruby in it.  I think this is a mistake ticket.
