### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by MichaelB2018** [stjohnjohnson/smartthings-mqtt-bridge#212]
Great work - absolutely love this project. Yet being a Python fan, I just had to port it... 

https://github.com/MichaelB2018/smartthings-mqtt-bridge

Also added additional an additional feature for Home Assistant's MQTT Discovery, to make setup simpler. Beside this, all the rest should be fully compatible.

**Comment by erenfro** [comment]
But, you can't even spell Python in your readme. Puython? :p

**Comment by MichaelB2018** [comment]
fixed that spelling mistake

**Comment by erenfro** [comment]
Egggcelent actually! Once I noticed this project hasn’t seen any updates in a long while and yours has started the process of mqtt discovery, I’ve already started using yours! Very good work! I’ll likely start adding issues and PRs as I can to improve what you’ve got!
