### ISSUE TITLE
Cant uninstall anything .. 

### ISSUE THREAD

**Issue by Tontze** [stjohnjohnson/smartthings-mqtt-bridge#217]
Was unable to get this working, classic app says unexpected error, so i thought to uninstall. But seems i cannot .. 

Cant uninstall smartapp from classic app or from ide, cant uninstall handler from ide, or device i created. 

Allways : 

![kuva](https://user-images.githubusercontent.com/28216916/82159166-0d5d7880-9895-11ea-83a3-e829a4b5f2b3.png)

Even force delete fails in IDE. Anyone managed to get past this ?

**Comment by erenfro** [comment]
I managed to get past this when I waited a bit.

**Comment by qwiksilver** [comment]
I get exactly the same thing and had to contact support. They removed the devices, device handler and the smartapp manually for me (Tier 2) only for it to happen again as soon as I attempted to re-configure everything. How on earth is it possible that third party code could wreak so much havoc on the smartthings ecosystem? It is ridiculous that Samsung has such functionality that can corrupt their database. I am giving up on Smart Things.

**Comment by Tontze** [comment]
I was able to get past this when i remembered that i tried smartthings app on ipad. I logged in to **samsung** account and removed ipad access from there, this did help me uninstall.
