### ISSUE TITLE
self signed certs are not supported

### ISSUE THREAD

**Issue by tusc** [stjohnjohnson/smartthings-mqtt-bridge#24]
I've been able to get mqtt-bridge to work with CloudMQTT but would like to setup my own private broker behind my firewall, with SSL enabled. Is this possible with mqtt-bridge? This is the error I get. Thanks.

ctalbot@homeassistant:~$ smartthings-mqtt-bridge
info: Starting SmartThings MQTT Bridge - v1.2.0
info: Loading configuration
info: Loading previous state
info: Perfoming configuration migration
info: Saving current state
info: Connecting to MQTT at mqtts://192.168.1.52:8883

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: SELF_SIGNED_CERT_IN_CHAIN
    at SecurePair.<anonymous> (tls.js:1370:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read] (tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)

contents of /opt/mqtt-bridge/config.yaml:

---
mqtt:
    # Specify your MQTT Broker's hostname or IP address here
    host: mqtts://192.168.1.52:8883
    # Preface for the topics $PREFACE/$DEVICE_NAME/$PROPERTY
    preface: smartthings
    username: smartmqtt
    password: XXXXXXXX

port: 8080

**Comment by stjohnjohnson** [comment]
Hmm, we support anything in the MQTT client we use: https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options

I wonder if you can pass an "ignore self signed cert" option.

**Comment by tusc** [comment]
From that page it appears there is an option: 

"If you are using a self-signed certificate, pass the rejectUnauthorized: false option."

How can this be represented in the conig.yml file? Thanks.

**Comment by stjohnjohnson** [comment]
Put it under the "mqtt:" heading, everything there is passed directly to
that connect function.
On Wed, Mar 9, 2016 at 08:05 tusc <notifications@github.com> wrote:

> From that page it appears there is an option:
>
> "If you are using a self-signed certificate, pass the rejectUnauthorized:
> false option."
>
> How can this be represented in the conig.yml file? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stjohnjohnson/smartthings-mqtt-bridge/issues/24#issuecomment-194365345>
> .
>
-- 
-St. John

**Comment by tusc** [comment]
Awsome! That worked, thanks!
