### ISSUE TITLE
Error from SmartThings Hub

### ISSUE THREAD

**Issue by tySwift93** [stjohnjohnson/smartthings-mqtt-bridge#29]
This has been happening the last couple of days. Seems to happen when I send an MQTT message to the bridge.

> error: Error from SmartThings Hub: Error: connect ETIMEDOUT 192.168.1.2:39500
error: {
    "code": "ETIMEDOUT",
    "errno": "ETIMEDOUT",
    "syscall": "connect",
    "address": "192.168.1.2",
    "port": 39500
}
error: undefined

I haven't changed anything in the last few days. Any suggestions?  Thanks

**Comment by stjohnjohnson** [comment]
Ahh, so that usually indicates one of two things:
 - did your hub change it's IP address?
 - did your bridge change it's IP address?

These usually causes this error as either the SmartThings hub is no longer where the bridge expects it OR the hub is denying requests because it doesn't know this new bridge's IP address.

**Comment by tySwift93** [comment]
Both devices have static IPs.  Any other known causes?  I fixed it by restarting the bridge, but I'd prefer not to do that once a day. For how I am using this, it is imperative that it successfully sends commands to ST and can receive them back.

By the way, when the issue was occurring I was still receiving messages from ST in the bridge, I just couldn’t send them!  Very weird. Thanks for looking into this!

**Comment by stjohnjohnson** [comment]
I've never seen it happen where only one of them can talk.  Very strange.  Sorry.

**Comment by tySwift93** [comment]
Not a problem. It hasn't happened since I started having the bridge auto-restart every day at 4am.
