### ISSUE TITLE
Where are the devices published?

### ISSUE THREAD

**Issue by fia5000** [stjohnjohnson/smartthings-mqtt-bridge#30]
I'm a little confused by the blog post on home-assistant.io

> Replace localhost with the location of the running MQTT Broker. Devices from the MQTT Bridge are published to the path smartthings/<Device Name>/<Atribute>

Where is this path?

**Comment by jer** [comment]
That is the path inside of MQTT. Events in MQTT are published and subscribed through path names, and by default the SmartThings bridge interacts at a path starting with 'smartthings/'

**Comment by jer** [comment]
Btw to see these events in your MQTT server, you can use an MQTT client to subscribe to smartthings/#

**Comment by fia5000** [comment]
@jer Thanks a bunch. I eventually figured it out. Everything works now.

**Comment by jer** [comment]
Awesome, glad to hear! Let us know if you hit any other snags.
