### ISSUE TITLE
Presence Not Updating

### ISSUE THREAD

**Issue by Mdleal** [stjohnjohnson/smartthings-mqtt-bridge#34]
events.log
`2016-04-18T16:57:42.226Z - info: Incoming message from MQTT: smartthings/Mike_Phone/presence = not present
2016-04-18T16:57:50.308Z - info: Incoming message from MQTT: smartthings/Mike_Phone/presence = present
`

Smartthings Log
`f78cb95f-c930-44b1-83d7-541b176fada4  11:57:50 AM: debug Received device event from bridge: [name:Mike_Phone, value:present, type:presence]
f78cb95f-c930-44b1-83d7-541b176fada4  11:57:42 AM: debug Received device event from bridge: [name:Mike_Phone, value:not present, type:presence]`

**Comment by stjohnjohnson** [comment]
Sadly SmartThings doesn't allow us to change the presence of a device, only read the current value: http://docs.smartthings.com/en/latest/capabilities-reference.html#presence-sensor  You can see here there are no commands we can call.

**Comment by Mdleal** [comment]
Well crap. Thanks for looking.

**Comment by tjb8907** [comment]
I use a simulated presence sensor. I don't have MQTT set up yet, but I use Tasker and SharpTools on my phone to update it
