### ISSUE TITLE
Issue with Bridge

### ISSUE THREAD

**Issue by rdrivas123** [stjohnjohnson/smartthings-mqtt-bridge#37]
Hello,

I see traffic in the MQTT and in my smart app, but I cant control any of my lights, etc.
I see commands going to the MQTT and to my smart app (called SH) .

But what are the commands I use to get my lights recognized and functioning?

Name	Value
archivable	true
commandId	168907
date	2016-04-23 10:05:17.785 PM EDT (2016-04-24T02:05:17.785Z)
description	
deviceId	2aa34a3b-45a3-463f-a78e-9162a27c4d17
displayed	true
eventSource	APP_COMMAND
hubId	5c157cfa-6335-4714-8620-6be7e072da6f
id	fdcd9ba0-09c0-11e6-8947-0643aaa66965
installedSmartAppId	b7eac426-6fc6-41fc-aaab-76ccd173314d
isStateChange	true
isVirtualHub	false
linkText	MQTT Bridge
locationId	50264796-314f-48ab-bb35-900757c6e0da
rawDescription	MQTT Bridge sent deviceNotification command to SH
smartAppId	55ec89dc-950c-4a00-83fd-cb7e7e5b1ee9
smartAppVersionId	b472088a-36aa-4ad6-97d0-1f05c11f2e6f
translatable	false
unixTime	1461463517785
value	deviceNotification
viewed	false

**Comment by stjohnjohnson** [comment]
is this different than #36 ?

**Comment by stjohnjohnson** [comment]
Closing in favor of #36
