### ISSUE TITLE
Color change via MQTT publish fails

### ISSUE THREAD

**Issue by tscopp** [stjohnjohnson/smartthings-mqtt-bridge#46]
I've found that when publishing to the hue or color topics of devices that support such things (in my case a [Zipato RGBW lightbulb](https://www.zipato.com/product/zipato-rgbw-bulb) and the [Fibaro RGBW controller](http://www.fibaro.com/us/the-fibaro-system/rgbw-controller)) messages related to color/hue are seen as far as the MQ but never have any effect on the devices. 

When changing a bulb via the smartthings app:

> smartthings-mqtt-bridge-0 info: Incoming message from MQTT: smartthings/Studio.Ambient/hue = 44.37908
> smartthings-mqtt-bridge-0 info: Incoming message from MQTT: smartthings/Studio.Notification/saturation = 100
> smartthings-mqtt-bridge-0 info: Incoming message from MQTT: smartthings/Studio.Notification/color = #FF9700
> smartthings-mqtt-bridge-0 info: Incoming message from SmartThings: smartthings/Studio.Ambient/level = 97

So one would think (assuming the MQ is working, mine is) that the following would accomplish the same (after, of course, changing the hue/color via the ST app):

> mosquitto_pub -h localhost -t "smartthings/Studio.Ambient/hue" -m "44.37908"
> mosquitto_pub -h localhost -t "smartthings/Studio.Ambient/saturation" -m "100"
> mosquitto_pub -h localhost -t "smartthings/Studio.Ambient/color" -m "#FF9700"
> mosquitto_pub -h localhost -t "smartthings/Studio.Ambient/level" -m "97"

But despite being seen on the MQ and in the logs of the mqtt-bridge they seem to have no effect.

> smartthings-mqtt-bridge-0 info: Incoming message from MQTT: smartthings/Studio.Ambient/hue = 44.37908
> smartthings-mqtt-bridge-0 info: Incoming message from MQTT: smartthings/Studio.Notification/saturation = 100
> smartthings-mqtt-bridge-0 info: Incoming message from MQTT: smartthings/Studio.Ambient/color = #FF9700
> smartthings-mqtt-bridge-0 info: Incoming message from MQTT: smartthings/Studio.Ambient/level = 99

**Comment by zifnab06** [comment]
Just put a PR in that fixes it. Enjoy! :smile:
