### ISSUE TITLE
Brightness issue

### ISSUE THREAD

**Issue by sabooker** [stjohnjohnson/smartthings-mqtt-bridge#50]
Having trouble adjusting brightness levels for switches/lights within HomeAssistant.

It will adjust the level, but only seems to work sometimes. Also, if I increase brightness in either smartthings or home-assistant, it will not update the other? Not sure if there is a template to use. I think part of the problem is home-assistant uses 1-255 for level, while smartthings seems to use 1-99.

light 2:
  platform: mqtt
  name: "Living Room Lamp"
  state_topic: "smartthings/Living Room Lamp/switch"
  command_topic: "smartthings/Living Room Lamp/switch"
  brightness_state_topic: "smartthings/Living Room Lamp/level"
  brightness_command_topic: "smartthings/Living Room Lamp/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

**Comment by stjohnjohnson** [comment]
Ahh, you want to set your `brightness_scale` in that config.  I added it to Home Assistant a long time back: https://home-assistant.io/components/light.mqtt/

Set it to 99

```
light 2:
    platform: mqtt
    name: "Living Room Lamp"
    state_topic: "smartthings/Living Room Lamp/switch"
    command_topic: "smartthings/Living Room Lamp/switch"
    brightness_state_topic: "smartthings/Living Room Lamp/level"
    brightness_command_topic: "smartthings/Living Room Lamp/level"
    payload_on: "on"
    payload_off: "off"
    retain: true
    brightness_scale: 99
```

**Comment by stjohnjohnson** [comment]
Did you try that?

**Comment by sabooker** [comment]
Yes, that worked great. Thanks so much!
