### ISSUE TITLE
Does it support SSL clients connections?

### ISSUE THREAD

**Issue by mvillarejo** [stjohnjohnson/smartthings-mqtt-bridge#81]
hello, do you have a method of using SSL certificates for authenticating with mqtt server?

thanks

**Comment by stjohnjohnson** [comment]
If this client supports it, yes. Client: https://www.npmjs.com/package/mqtt#client

**Comment by mvillarejo** [comment]
Yeah, saw that but couldn't find the config arguments for SSL certificate path any idea?

**Comment by gandazgul** [comment]
@mvillarejo add this to the config:

mqtt:
    # Specify your MQTT Broker's hostname or IP address here
    host: tls://localhost:8883
    rejectUnauthorized: false
... rest here

**Comment by mvillarejo** [comment]
yes, finally managed to make it work.
this can be closed.

thanks.
