### ISSUE TITLE
Unable to change Virtual Presence device

### ISSUE THREAD

**Issue by ScottChapman** [stjohnjohnson/smartthings-mqtt-bridge#86]
I have a virtual presence device, and I can watch the message that get sent when I trigger it from the ST app. But when I send the same messages to the topic nothing happens.

I have confirmed that other devices (like my light) work like a charm.

**Comment by ScottChapman** [comment]
OK, I see the issue. No action associated with the device type.

I've never done smartapps before, so I don't feel real comfortable just giving it a go.

But it looks fairly simple; listen for "present" or "not present" on the topic and set the state of the device accordingly.

Anyone care to help please?

**Comment by ScottChapman** [comment]
Meh, took a crack at it. This appears to work:

https://github.com/stjohnjohnson/smartthings-mqtt-bridge/pull/87

**Comment by ScottChapman** [comment]
OK, got it. this works!

**Comment by stjohnjohnson** [comment]
Thanks for the contribution!
