### ISSUE TITLE
MQTT Messages not being sent to broker

### ISSUE THREAD

**Issue by cizzop** [stjohnjohnson/smartthings-mqtt-bridge#91]
I am seeing this in the smartthings live log:

Forwarding device event to bridge: {"path":"/push","body":{"name":"Bedroom Lamp","value":"on","type":"switch"}}

However, I am not seeing anything in my Mosquitto broker when subscribing to all topics. (i.e. mosquitto_sub -v -t '#') 

I have set the IP, port and MAC in the device settings. 

Is this now broken?

**Comment by stjohnjohnson** [comment]
@cizzop was it working before?  Has anything changed on your network?  Does SmartThings and the MQTT Bridge still have the same IPs?  What are the contents of the Bridge logs?

**Comment by cizzop** [comment]
@stjohnjohnson I appreciate the quick response! No I have not ever had this working. I have both smartthings and my MQTT broker (mosquitto running on a raspberry pi) set as a static IP address so the addresses have not changed. What effect would changing the smartthings hub IP address have? I understand why changing the MQTT IP would break things. 

To be clear... the MAC address asked for in the parameters should be the MAC of the ethernet port of my raspberry pi correct? This is where I have mosquitto running.

**Comment by stjohnjohnson** [comment]
If the SmartThings hub IP changes, MQTT Bridge can't send a message back.  What are the contents of the MQTT Bridge logs?

And yes, the MAC address should be the Raspberry Pi (if that's where the bridge is running).

**Comment by cizzop** [comment]
@stjohnjohnson In the MQTT device logs I am seeing an event happen in this order:

1. MQTT App sent deviceNotification command to MQTT Device
2. deviceNotification({"path":"/push","body":{"name":"Bedroom Lamp","value":"on","type":"switch"}}) command was sent to MQTT Device

Are these the logs you are asking for?

**Comment by stjohnjohnson** [comment]
No, I'm referring to the MQTT Bridge server code.  Are you using Docker or NPM to run the service?  See https://github.com/stjohnjohnson/smartthings-mqtt-bridge#installation for more details about either option.

**Comment by cizzop** [comment]
@stjohnjohnson I apologize. I think I completely mis-understood this part. I assumed that I could use basically any MQTT broker which is why I am using Mosquitto... I will attempt to use this broker via NPM. Thanks for creating this awesome project.

**Comment by cizzop** [comment]
OK. I now have the bridge up and running with npm. I start the service using pm2 I can see this when looking at the log:

`0|smartthi | info: Saving current state
0|smartthi | info: Connecting to MQTT at mqtt://192.168.1.40
0|smartthi | info: Configuring autosave
0|smartthi | info: Configuring API
0|smartthi | info: Listening at http://localhost:8090`


These settings look completely correct to me as I have mosquitto running at 192.168.1.40 and I have my smartthings settings pointed to port 8090. In my smartthings live logging I can messages suggesting that things are working fine...

`8295d6e9-6054-4de4-ba0b-be39a7440f4c  2:36:04 PM: debug Forwarding device event to bridge: {"path":"/push","body":{"name":"OfficeLamp","value":"off","type":"switch"}}
8835d3ed-913d-40ef-a5d5-ef44d07ec9f6  2:36:04 PM: debug Sending '{"path":"/push","body":{"name":"OfficeLamp","value":"off","type":"switch"}}' to device`


However, I am not seeing anything pop up in the smartthings-mqtt-bridge logs. Is there anything else I can look at to help me debug?

**Comment by cizzop** [comment]
Hallelujah! After power cycling my smartthings hub (again) it magically kicked on. All is working beautifully now. Thanks for the help!
