### ISSUE TITLE
MQTT API Question

### ISSUE THREAD

**Issue by mschwartz** [stjohnjohnson/smartthings-mqtt-bridge#95]
It seems to me the MQTT API is a bit confounding and might be done better.

Right now, you get something like 

```
smartthings/Light/switch on
```

And you send the same thing to turn that switch on.  

The issue is you will then receive the message you sent because you're subscribed/istening.

My suggestion is to have incoming messages something like:

```
smartthings/status/Light/switch on
```

For incoming messages

And you send:

```
smartthings/set/Light/switch on
```

To control the device.

This way, you won't get the "set" message that you sent.

This suggestion allows you to listen on 

```
smartthings/status/#
```

And you only get true status messages

**Comment by stjohnjohnson** [comment]
Yup!  We do have that feature.  It's turned off by default for backwards compatibility, but you just need to set the command_suffix and state_suffix: https://github.com/stjohnjohnson/smartthings-mqtt-bridge#configuration

**Comment by mschwartz** [comment]
Awesome.  I'm all over that!

**Comment by mschwartz** [comment]
This project inspired me:

https://github.com/autodomo

I need to change the name, though.

**Comment by mschwartz** [comment]
I changed the name to RoboDomo.

So the url is now:
https://github.com/robodomo

Thanks for your work!

**Comment by mschwartz** [comment]
Sorry, the feature isn't as I want :(

```
smartthings/Kitchen Lights/switch/status off
```

Isn't want I want

I want:

```
smartthings/Kitchen Light/status/switch off
```

parsing is trivial:

```
const TOPIC = `smartthings/${device}/status/'
MQTT.subscribe(TOPIC + '#'
MQTT.onMessage((topic, message) => {
    const thing = topic.substr(TOPIC.length) // =-> switch, level, whatever
    ...
})
```

**Comment by mschwartz** [comment]
```javascript
    componentDidMount() {
        MQTT.subscribe(this.status_topic + 'switch', this.onStateChange)
        MQTT.subscribe(this.status_topic + 'level', this.onStateChange)
    }
```

**Comment by mschwartz** [comment]
```javascript
    onStateChange(topic, newState) {
        const newValue = {},
              key     = topic.substr(this.status_topic.length)

        newValue[key] = newState
        this.setState(newValue)
    }
```

**Comment by mschwartz** [comment]
I figured out a trick.  I'm hoping all this helps someone else who stumbles onto this ticket.

no state_suffix, but use a command_prefix

That JS code above that I posted works fine without the /state/ present in the topic.

To send, just MQTT.publish(this.set_topic + 'switch/set', 'on')

Not too ugly :)

**Comment by stjohnjohnson** [comment]
Glad you found a workaround!
