### ISSUE TITLE
Smart home monitor support

### ISSUE THREAD

**Issue by mvillarejo** [stjohnjohnson/smartthings-mqtt-bridge#99]
Do you think it would be too difficult to add support for smart home monitor (alarm) it would be great to make it work with new home assistant mqtt alarm component.
https://home-assistant.io/components/alarm_control_panel.mqtt/
Thanks

**Comment by mvillarejo** [comment]
Does someone have an idea how to start with this at least? Thanks

**Comment by jamieboy05** [comment]
Been done already https://ethitter.com/2016/08/smartthings-smart-home-monitor-shm-mqtt-home-assistant/

**Comment by mvillarejo** [comment]
That's really great, have you considered creating a github repo for it? I'll be testing it today as soon as I arrive home! cheers!

**Comment by jamieboy05** [comment]
It's not my code, I was just passing along my findings. I personally have used it for the good part of a year, works flawlessly.

**Comment by mvillarejo** [comment]
great, thanks! closing this now.
